version: "3"
services:
  mail:
    environment:
      - FLUX_MAIL_FETCH_HOST=...
      - FLUX_MAIL_FETCH_PORT=993
      - FLUX_MAIL_FETCH_TYPE=imap
      - FLUX_MAIL_FETCH_USER_NAME=...
      - FLUX_MAIL_FETCH_PASSWORD=...
      - FLUX_MAIL_FETCH_ENCRYPTION_TYPE=tls-auto
      - FLUX_MAIL_SMTP_HOST=...
      - FLUX_MAIL_SMTP_PORT=465
      - FLUX_MAIL_SMTP_ENCRYPTION_TYPE=tls-auto
      - FLUX_MAIL_SMTP_USER_NAME=...
      - FLUX_MAIL_SMTP_PASSWORD=...
      - FLUX_MAIL_SEND_FROM=...
      - FLUX_MAIL_SEND_FROM_NAME=...
    image: docker-registry.fluxpublisher.ch/flux-mail:latest
    restart: always
  other_service:
    environment:
      [- FLUX_MAIL_HOST=mail]
      [- FLUX_MAIL_PORT=9501]
