version: "3"
services:
  mail-api:
    environment:
      - FLUX_MAIL_API_MAIL_HOST=...
      - FLUX_MAIL_API_MAIL_PORT=993
      - FLUX_MAIL_API_MAIL_TYPE=imap
      - FLUX_MAIL_API_MAIL_USER_NAME=...
      - FLUX_MAIL_API_MAIL_PASSWORD=...
      - FLUX_MAIL_API_MAIL_ENCRYPTION_TYPE=tls-auto
      - FLUX_MAIL_API_SMTP_HOST=...
      - FLUX_MAIL_API_SMTP_PORT=465
      - FLUX_MAIL_API_SMTP_ENCRYPTION_TYPE=tls-auto
      - FLUX_MAIL_API_SMTP_USER_NAME=...
      - FLUX_MAIL_API_SMTP_PASSWORD=...
      - FLUX_MAIL_API_SMTP_FROM=...
      - FLUX_MAIL_API_SMTP_FROM_NAME=...
    image: docker-registry.fluxpublisher.ch/flux-mail/api:latest
    restart: always
  other-service:
    environment:
      [- FLUX_MAIL_API_HOST=mail-api]
      [- FLUX_MAIL_API_PORT=9501]
