version: "3"
services:
  mail-api:
    environment:
      - FLUX_MAIL_API_FETCH_HOST=...
      - FLUX_MAIL_API_FETCH_PORT=993
      - FLUX_MAIL_API_FETCH_TYPE=imap
      - FLUX_MAIL_API_FETCH_USER_NAME=...
      - FLUX_MAIL_API_FETCH_PASSWORD=...
      - FLUX_MAIL_API_FETCH_ENCRYPTION_TYPE=tls-auto
      - FLUX_MAIL_API_SMTP_HOST=...
      - FLUX_MAIL_API_SMTP_PORT=465
      - FLUX_MAIL_API_SMTP_ENCRYPTION_TYPE=tls-auto
      - FLUX_MAIL_API_SMTP_USER_NAME=...
      - FLUX_MAIL_API_SMTP_PASSWORD=...
      - FLUX_MAIL_API_SEND_FROM=...
      - FLUX_MAIL_API_SEND_FROM_NAME=...
    image: docker-registry.fluxpublisher.ch/flux-mail/api:latest
    restart: always
  other-service:
    environment:
      [- FLUX_MAIL_API_HOST=mail-api]
      [- FLUX_MAIL_API_PORT=9501]
