version: "3"
services:
  mail-api:
    environment:
      - FLUX_MAIL_API_FETCH_HOST=...
      - FLUX_MAIL_API_FETCH_PORT=993
      - FLUX_MAIL_API_FETCH_TYPE=imap
      - FLUX_MAIL_API_FETCH_USER_NAME=...
      - FLUX_MAIL_API_FETCH_PASSWORD=...
      - FLUX_MAIL_API_FETCH_ENCRYPTION_TYPE=tls-auto
      - FLUX_MAIL_API_FETCH_MARK_AS_READ=false
      - FLUX_MAIL_API_SMTP_HOST=smtp
      - FLUX_MAIL_API_SMTP_PORT=1025
      - FLUX_MAIL_API_SEND_FROM=from@test.local
      - FLUX_MAIL_API_SEND_FROM_NAME=Test From User
    image: docker-registry.fluxpublisher.ch/flux-mail/api:latest
    ports:
      - [%host_ip%:]9501:9501
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - [%host_ip%:]8025:8025
  other-service:
    environment:
      [- FLUX_MAIL_API_HOST=mail-api]
      [- FLUX_MAIL_API_PORT=9501]
